import java.io.File
import java.nio.file.Files
import java.security.MessageDigest

group 'com.alexmercerind.media_kit_libs_android_video'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    // Conditional for compatibility with AGP <4.2.
    if (project.android.hasProperty("namespace")) {
        namespace 'com.alexmercerind.media_kit_libs_android_video'
    }

    compileSdkVersion 36

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 16
    }

    dependencies {
        implementation fileTree(dir: "$buildDir/output", include: "*.jar")
    }
}

task downloadDependencies(type: Exec) {   
        // Delete previously created /output subdirectory.

        def outputDir = file("$buildDir/output")
        if (outputDir.exists()) {
            outputDir.deleteDir()
        }
        outputDir.mkdirs()

        // Download all *.jar dependencies & verify their SHA-256 checksums.
        def filesToDownload = [
            ["url": "https://github.com/xweiba/libmpv-android-video-build/releases/download/v1.2.7-mediaio.2/default-arm64-v8a.jar", "sha256": "a2475f4360762ab28e44246c0b16eb66a72da0c7263f6fd2166023ab759ba41d", "destination": file("$buildDir/v1.2.7-mediaio.2/default-arm64-v8a.jar")],
            ["url": "https://github.com/xweiba/libmpv-android-video-build/releases/download/v1.2.7-mediaio.2/default-armeabi-v7a.jar", "sha256": "888abf10e2c3a09afda3d49bb950ef58314c6fb86cf3f6324fef609340edfc7c", "destination": file("$buildDir/v1.2.7-mediaio.2/default-armeabi-v7a.jar")],
            ["url": "https://github.com/xweiba/libmpv-android-video-build/releases/download/v1.2.7-mediaio.2/default-x86_64.jar", "sha256": "a9abc18d1e0f8747bd35f8bfb1dee66b12d437c30e9042792dcc172949d2acac", "destination": file("$buildDir/v1.2.7-mediaio.2/default-x86_64.jar")],
            ["url": "https://github.com/xweiba/libmpv-android-video-build/releases/download/v1.2.7-mediaio.2/default-x86.jar", "sha256": "1d8b571cc642599f8b738d1e2f28938972c74d5ae9d33c1811929fc833f4265a", "destination": file("$buildDir/v1.2.7-mediaio.2/default-x86.jar")]
        ]

        filesToDownload.each { fileInfo ->
            def destFile = fileInfo.destination
            if (destFile.exists()) {
                def calculatedSHA256 = MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(destFile.toPath())).encodeHex().toString()

                if (calculatedSHA256 != fileInfo.sha256) {
                    destFile.delete()
                    println "SHA-256 mismatch. File deleted: ${destFile}"
                }

            }

            if (!destFile.exists()) {
                destFile.parentFile.mkdirs()
                println "Downloading file from: ${fileInfo.url}"
                destFile.withOutputStream { os ->
                    os << new URL(fileInfo.url).openStream()
                }

                def calculatedSHA256 = MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(destFile.toPath())).encodeHex().toString()
                if (calculatedSHA256 != fileInfo.sha256) {
                    throw new GradleException("SHA-256 verification failed for ${destFile}")
                }
            }

            copy {
                from destFile
                into outputDir
            }
        }
}

assemble.dependsOn(downloadDependencies)
