import java.io.File
import java.nio.file.Files
import java.security.MessageDigest

group 'com.alexmercerind.media_kit_libs_android_video'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    // Conditional for compatibility with AGP <4.2.
    if (project.android.hasProperty("namespace")) {
        namespace 'com.alexmercerind.media_kit_libs_android_video'
    }

    compileSdkVersion 36

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 16
    }

    dependencies {
        implementation fileTree(dir: "$buildDir/output", include: "*.jar")
    }
}

task downloadDependencies(type: Exec) {   
        // Delete previously created /output subdirectory.

        def outputDir = file("$buildDir/output")
        if (outputDir.exists()) {
            outputDir.deleteDir()
        }
        outputDir.mkdirs()

        // Download all *.jar dependencies & verify their SHA-256 checksums.
        def filesToDownload = [
            ["url": "https://github.com/xweiba/libmpv-android-video-build/releases/download/v1.2.7-mediaio.1/default-arm64-v8a.jar", "sha256": "3b30f26248615107d0cc81368ea0ca89fdfe856d590298aa0bce19c219b008b1", "destination": file("$buildDir/v1.2.7-mediaio.1/default-arm64-v8a.jar")],
            ["url": "https://github.com/xweiba/libmpv-android-video-build/releases/download/v1.2.7-mediaio.1/default-armeabi-v7a.jar", "sha256": "0542a9476d5f866eea36a658e0988edccfb6b00d267dedddb6947ed9586add8c", "destination": file("$buildDir/v1.2.7-mediaio.1/default-armeabi-v7a.jar")],
            ["url": "https://github.com/xweiba/libmpv-android-video-build/releases/download/v1.2.7-mediaio.1/default-x86_64.jar", "sha256": "b48d062262ca336672565c63f1a49a718108b84382f63e8b08e98712c6adbbc7", "destination": file("$buildDir/v1.2.7-mediaio.1/default-x86_64.jar")],
            ["url": "https://github.com/xweiba/libmpv-android-video-build/releases/download/v1.2.7-mediaio.1/default-x86.jar", "sha256": "fa430b70b059be13430552f61cfa07938a6a60fb48176990ef992fee370dbf57", "destination": file("$buildDir/v1.2.7-mediaio.1/default-x86.jar")]
        ]

        filesToDownload.each { fileInfo ->
            def destFile = fileInfo.destination
            if (destFile.exists()) {
                def calculatedSHA256 = MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(destFile.toPath())).encodeHex().toString()

                if (calculatedSHA256 != fileInfo.sha256) {
                    destFile.delete()
                    println "SHA-256 mismatch. File deleted: ${destFile}"
                }

            }

            if (!destFile.exists()) {
                destFile.parentFile.mkdirs()
                println "Downloading file from: ${fileInfo.url}"
                destFile.withOutputStream { os ->
                    os << new URL(fileInfo.url).openStream()
                }

                def calculatedSHA256 = MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(destFile.toPath())).encodeHex().toString()
                if (calculatedSHA256 != fileInfo.sha256) {
                    throw new GradleException("SHA-256 verification failed for ${destFile}")
                }
            }

            copy {
                from destFile
                into outputDir
            }
        }
}

assemble.dependsOn(downloadDependencies)
